### ISSUE TITLE
Creating a PercentOutput DriveSystem

### ISSUE THREAD

**Issue by frc4533dev** [wando-advanced-robotics/DeepSpaceRobot#10]
Creating a percent output drive system will allow us to drive the robot when we are done with it. This entails creating a method in drive system and a new command called driveCommand.

**Comment by BearsAreAwsome** [comment]
To create the percent output method in DriveSystem, you will need two parameters. Assuming that we are driving with tank drive this year we will need a left joystick value and a right joystick value. The motor controllers should be set to those values here.

To create the DriveCommand class we have to recreate the command package as it was accidentally deleted when ExampleCommand class was created. If I am correct it should be as easy as right clicking on the robot PACKAGE (not the class), clicking new folder and naming it commands. Then create a new class through the wpilib button with the type being command. In this command we need a Joystick object, and a DriveSystem object that equals DriveSystem.initialize(). The execute method should contain the DriveSystem method you created with the parameters  of that method being the joystick values got through joystickObject.getRawAxis(axisID);. You can get the axisID from DriverStation.

**Comment by BearsAreAwsome** [comment]
Done
