### ISSUE TITLE
Remove Template Code

### ISSUE THREAD

**Issue by BearsAreAwsome** [wando-advanced-robotics/DeepSpaceRobot#2]
Some code that is auto generated by WPI for creating a command based robot is not needed. This task involves removing ExampleSubsystem and its references, ExampleCommand and its references, m_autonomousCommand and its references in Robot (comment out the if statement in the autonomousInit and teleopInit method), m_chooser and its references in Robot, and stuff that references SmartDashboard in Robot.

**Comment by asvaliveti** [comment]
code was removed
