### ISSUE TITLE
Create Position Control Mode

### ISSUE THREAD

**Issue by BearsAreAwsome** [wando-advanced-robotics/DeepSpaceRobot#21]
Position control mode was used for autonomous last year. It might not be as important as last year to create it, as autonomous functions seem to be more focused on cameras this year, but it is important to at least create it.

**Comment by BearsAreAwsome** [comment]
To create a position drive mode, we first need to set up the magnetic encoders. To do this we use the method .configSelectedFeedbackSensor(). It has three parameters, the encoder that we are using (CTRE magnetic encoder), the PID index which is 0, and the timeout ms, which is 100.

**Comment by tacoberb** [comment]
closed as a taco is delicious
