### ISSUE TITLE
Install the FRC Update Suite on all Robotics Laptops

### ISSUE THREAD

**Issue by BearsAreAwsome** [wando-advanced-robotics/DeepSpaceRobot#5]
This is a major priority. Coding should not start until the update is at least running on the main coding laptop. This update takes forever and must be completed so that we can update the roboRios and radios.

**Comment by asvaliveti** [comment]
FRC update suite installed on some laptops.

**Comment by BearsAreAwsome** [comment]
FRC update suite is installed on all laptops as of last meeting.
