### ISSUE TITLE
Install VSCode on the coding laptops

### ISSUE THREAD

**Issue by BearsAreAwsome** [wando-advanced-robotics/DeepSpaceRobot#6]
This is a priority if we are going to be using the coding laptops at all this year. Otherwise we can't code at all at school if we don't bring our personal laptops.

**Comment by abrightwell** [comment]
Is this necessary? Are we not going to use the same workflow of using Gradle and IntelliJ?

**Comment by BearsAreAwsome** [comment]
It might not be necessary if we continue to use IntelliJ, however I feel like it is a good idea to try out VSCode for at least this year as First switched from eclipse to VSCode this year. If we don't like it, we can always to switch back to IntelliJ.

**Comment by abrightwell** [comment]
Ok, seems like a sound plan to me. As the lead programmer, I'll leave it up to you.

**Comment by BearsAreAwsome** [comment]
These are some other reasons why I think that VSCode would be the easiest to use for this season. Since First also is no longer using eclipse, they most likely will not be updating the FRC plugins for eclipse, so eclipse would be hard to use. I don't know/remember the difficulty in setting up gradle in IntelliJ to do tasks such as building and deploying code, as I don't believe that I was the one to implement gradle in the code last year (and if I did I don't remember doing it). VSCode would probably be the easiest IDE to use, as we don't have to go do a bunch of things with gradle as it is included when you create new robot code.

**Comment by abrightwell** [comment]
All good points. And I believe Scott was the one that set the project up with gradle.

**Comment by asvaliveti** [comment]
All coding laptops are done
