### ISSUE TITLE
Adding Talon SRX objects

### ISSUE THREAD

**Issue by frc4533dev** [wando-advanced-robotics/DeepSpaceRobot#9]
To be able to drive the robot we need to program in the motor controller objects. Here is an example to how it will look. (Replace foo with left and right masters and slaves).
TalonSRX fooMaster;
public DriveSystem() {
     fooMaster = new TalonSRX(portID);
}

**Comment by asvaliveti** [comment]
need to add Talon values

**Comment by BearsAreAwsome** [comment]
Added IDs in latest commit.
